version: '3.8'

services:
  #-------------------------------#
  # 🖥️ Express                    #
  #-------------------------------#
  express:
    container_name: express_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - test-network
    restart: on-failure
    links:
      - mongo_db

  #-------------------------------#
  # 🖥️ MongoDB                    #
  #-------------------------------#
  mongo_db:
    image: mongo:4.2.12
    ports:
      - "27017:27017"
    environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - test-network

  #-------------------------------#
  # 🖥️ Mongo Express              #
  #-------------------------------#
  mongo_express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=mydb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
    ports:
      - "8083:8081"
    restart: on-failure
    depends_on:
      - mongo_db
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
